FROM ubuntu:22.04

EXPOSE 8000 8100 8200

RUN apt update && \
    apt install -y git python3-pip python3.11-dev libpcap-dev iproute2
RUN pip install poetry==1.8.0


WORKDIR /opencxl-core

ENTRYPOINT ["/bin/bash", "-c" , "poetry env use 3.11 && poetry install && sleep infinity"]
